DROP TABLE "COMMENT_REPORT"    PURGE;
DROP TABLE "COMMENT"           PURGE;
DROP TABLE "BOARD_LIKE"        PURGE;
DROP TABLE "BOARD_FILE"        PURGE;
DROP TABLE "BOARD"             PURGE;
DROP TABLE "BOARD_CATEGORY"    PURGE;
DROP TABLE "BOARD_TYPE"        PURGE;
DROP TABLE "FAQ"               PURGE;
DROP TABLE "NOTICE"            PURGE;
DROP TABLE "INQUIRY"           PURGE;
DROP TABLE "REVIEW"            PURGE;
DROP TABLE "STATUS"            PURGE;
DROP TABLE "DELIVERY"          PURGE;
DROP TABLE "ORDER_DETAIL"      PURGE;
DROP TABLE "ORDERS"            PURGE;
DROP TABLE "RECENTLY_VIEWED"   PURGE;
DROP TABLE "WISHLIST"          PURGE;
DROP TABLE "CART"              PURGE;
DROP TABLE "PET"               PURGE;
DROP TABLE "PRODUCT"           PURGE;
DROP TABLE "PRODUCT_CATEGORY"  PURGE;
DROP TABLE "COMPANY"           PURGE;
DROP TABLE "PERSISTENT_LOGINS" PURGE;
DROP TABLE "AUTHORITIES"       PURGE;
DROP TABLE "MEMBER"            PURGE;

CREATE TABLE "MEMBER" (
    "MEMBER_NO"         NUMBER          NOT NULL,
    "MEMBER_ID"         VARCHAR2(50)    NOT NULL,
    "MEMBER_PWD"         VARCHAR2(255)   NOT NULL,
    "MEMBER_NAME"       VARCHAR2(50)    NOT NULL,
    "MEMBER_ADDRESS"    VARCHAR2(200)   NOT NULL,
    "PHONE"             VARCHAR2(20)    NOT NULL,
    "EMAIL"             VARCHAR2(100)   NULL,
    "MEMBER_JOIN_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "MEMBER_ACTIVE_YN"  CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY ("MEMBER_NO")
);

CREATE TABLE "AUTHORITIES" (
    "MEMBER_NO"  NUMBER       NOT NULL,
    "AUTHORITY"  VARCHAR2(15) NULL,
    CONSTRAINT PK_AUTHORITIES PRIMARY KEY ("MEMBER_NO"),
    CONSTRAINT FK_AUTHORITIES_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "PERSISTENT_LOGINS" (
    "TOKEN"     VARCHAR2(64) NULL,
    "SERIES"    VARCHAR2(64) NULL,
    "LAST_USED" TIMESTAMP(6) NULL,
    "USERNAME"  VARCHAR2(64) NULL
);

-- [수정] CATEGORY_PARENT_ID: NOT NULL -> NULL (NULL=최상위 카테고리)
CREATE TABLE "PRODUCT_CATEGORY" (
    "CATEGORY_ID"        NUMBER       NOT NULL,
    "CATEGORY_NAME"      VARCHAR2(50) NOT NULL,
    "CATEGORY_PARENT_ID" NUMBER       NULL,
    CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY ("CATEGORY_ID")
);

COMMENT ON COLUMN "PRODUCT_CATEGORY"."CATEGORY_PARENT_ID" IS '상위 카테고리 ID (자기참조, NULL=최상위)';

ALTER TABLE "PRODUCT_CATEGORY" ADD CONSTRAINT FK_PRODUCT_CATEGORY_SELF
    FOREIGN KEY ("CATEGORY_PARENT_ID") REFERENCES "PRODUCT_CATEGORY" ("CATEGORY_ID");

CREATE TABLE "COMPANY" (
    "COMPANY_CODE"    NUMBER        NOT NULL,
    "COMPANY_NAME"    VARCHAR2(100) NULL,
    "COMPANY_PHONE"   VARCHAR2(20)  NULL,
    "ADDRESS_ADDRESS" VARCHAR2(200) NULL,
    CONSTRAINT PK_COMPANY PRIMARY KEY ("COMPANY_CODE")
);

CREATE TABLE "PRODUCT" (
    "PRODUCT_ID"        NUMBER        NOT NULL,
    "CATEGORY_ID"       NUMBER        NOT NULL,
    "COMPANY_CODE"      NUMBER        NOT NULL,
    "PRODUCT_NAME"      VARCHAR2(200) NOT NULL,
    "PRODUCT_PRICE"     NUMBER        NOT NULL,
    "PRODUCT_STOCK"     NUMBER DEFAULT 0 NOT NULL,
    "PRODUCT_DETAIL"    CLOB          NOT NULL,
    "PRODUCT_PHOTO1"    VARCHAR2(300) NOT NULL,
    "PRODUCT_PHOTO2"    VARCHAR2(300) NULL,
    "PRODUCT_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "PRODUCT_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    "PET_TYPE"          VARCHAR2(10)  NULL,
    "AGE_GROUP"         VARCHAR2(10)  NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY ("PRODUCT_ID"),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY ("CATEGORY_ID")  REFERENCES "PRODUCT_CATEGORY" ("CATEGORY_ID"),
    CONSTRAINT FK_PRODUCT_COMPANY  FOREIGN KEY ("COMPANY_CODE") REFERENCES "COMPANY"          ("COMPANY_CODE")
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_ACTIVE_YN" IS '품절되면 N으로 바뀌게';

CREATE TABLE "PET" (
    "PET_NO"     NUMBER        NOT NULL,
    "MEMBER_NO"  NUMBER        NOT NULL,
    "PET_TYPE"   VARCHAR2(20)  NOT NULL,
    "PET_NAME"   VARCHAR2(50)  NOT NULL,
    "PET_AGE"    DATE          NULL,
    "PET_WEIGHT" NUMBER(5,2)   NULL,
    "PET_PHOTO"  VARCHAR2(300) NULL,
    CONSTRAINT PK_PET PRIMARY KEY ("PET_NO"),
    CONSTRAINT FK_PET_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

COMMENT ON COLUMN "PET"."PET_PHOTO" IS '사진 파일 경로 (서버 상대경로)';

CREATE TABLE "CART" (
    "CART_ID"       NUMBER NOT NULL,
    "MEMBER_NO"     NUMBER NOT NULL,
    "PRODUCT_ID"    NUMBER NOT NULL,
    "CART_QTY"      NUMBER NOT NULL,
    "CART_REG_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CART PRIMARY KEY ("CART_ID"),
    CONSTRAINT FK_CART_MEMBER  FOREIGN KEY ("MEMBER_NO")  REFERENCES "MEMBER"  ("MEMBER_NO"),
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "WISHLIST" (
    "WISH_ID"    NUMBER NOT NULL,
    "MEMBER_NO"  NUMBER NOT NULL,
    "PRODUCT_ID" NUMBER NOT NULL,
    "WISH_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_WISHLIST PRIMARY KEY ("WISH_ID"),
    CONSTRAINT FK_WISHLIST_MEMBER  FOREIGN KEY ("MEMBER_NO")  REFERENCES "MEMBER"  ("MEMBER_NO"),
    CONSTRAINT FK_WISHLIST_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "RECENTLY_VIEWED" (
    "VIEW_ID"     NUMBER NOT NULL,
    "MEMBER_NO"   NUMBER NOT NULL,
    "PRODUCT_ID"  NUMBER NOT NULL,
    "VIEWED_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RECENTLY_VIEWED PRIMARY KEY ("VIEW_ID"),
    CONSTRAINT FK_RECENTLY_VIEWED_MEMBER  FOREIGN KEY ("MEMBER_NO")  REFERENCES "MEMBER"  ("MEMBER_NO"),
    CONSTRAINT FK_RECENTLY_VIEWED_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "ORDERS" (
    "ORDER_ID"            NUMBER        NOT NULL,
    "MEMBER_NO"           NUMBER        NOT NULL,
    "ORDER_DATE"          DATE DEFAULT SYSDATE NOT NULL,
    "ORDER_TOTAL_PRICE"   NUMBER        NOT NULL,
    "ORDER_DELIVERY_FEE"  NUMBER        NOT NULL,
    "ORDERER_NAME"        VARCHAR2(50)  NOT NULL,
    "ORDERER_PHONE"       VARCHAR2(20)  NOT NULL,
    "ORDERER_EMAIL"       VARCHAR2(100) NULL,
    "RECV_NAME"           VARCHAR2(50)  NOT NULL,
    "RECV_ADDRESS"        VARCHAR2(200) NOT NULL,
    "RECV_PHONE"          VARCHAR2(20)  NOT NULL,
    "ORDER_MEMO"          VARCHAR2(300) NULL,
    "ORDER_CANCEL_YN"     CHAR(1) DEFAULT 'N' NOT NULL,
    "CANCEL_REQUEST_DATE" DATE          NULL,
    "CANCEL_REASON"       VARCHAR2(200) NULL,
    "CANCEL_STATUS"       VARCHAR2(10)  NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY ("ORDER_ID"),
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "ORDER_DETAIL" (
    "DETAIL_ID"    NUMBER NOT NULL,
    "ORDER_ID"     NUMBER NOT NULL,
    "PRODUCT_ID"   NUMBER NOT NULL,
    "DETAIL_QTY"   NUMBER NULL,
    "DETAIL_PRICE" NUMBER NULL,
    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY ("DETAIL_ID"),
    CONSTRAINT FK_ORDER_DETAIL_ORDERS  FOREIGN KEY ("ORDER_ID")   REFERENCES "ORDERS"  ("ORDER_ID"),
    CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "DELIVERY" (
    "DELIVERY_ID"   NUMBER       NOT NULL,
    "ORDER_ID"      NUMBER       NOT NULL,
    "COURIER"       VARCHAR2(50) NULL,
    "EXPECTED_DATE" DATE         NULL,
    CONSTRAINT PK_DELIVERY PRIMARY KEY ("DELIVERY_ID"),
    CONSTRAINT FK_DELIVERY_ORDERS FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS" ("ORDER_ID")
);

CREATE TABLE "STATUS" (
    "DNUM"            VARCHAR2(50) NOT NULL,
    "DELIVERY_YN"     CHAR(1)      NULL,
    "DELIVERY_STATUS" VARCHAR2(20) NOT NULL,
    "DELIVERY_ID"     NUMBER       NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY ("DNUM"),
    CONSTRAINT FK_STATUS_DELIVERY FOREIGN KEY ("DELIVERY_ID") REFERENCES "DELIVERY" ("DELIVERY_ID")
);

COMMENT ON COLUMN "STATUS"."DELIVERY_STATUS" IS '배송중/배송완료 둘 중 하나의 값. 배송완료가 Y로 되어 있으면 배송 완료로 값을 변경';

-- [수정] REVIEW_RATING CHECK 제약 추가 (1~5 별점)
CREATE TABLE "REVIEW" (
    "REVIEW_ID"        NUMBER         NOT NULL,
    "MEMBER_NO"        NUMBER         NOT NULL,
    "DETAIL_ID"        NUMBER         NOT NULL,
    "REVIEW_RATING"    NUMBER(1)      NOT NULL,
    "REVIEW_CONTENT"   VARCHAR2(1000) NOT NULL,
    "REVIEW_PHOTO"     VARCHAR2(300)  NULL,
    "REVIEW_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "REVIEW_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REVIEW PRIMARY KEY ("REVIEW_ID"),
    CONSTRAINT CHK_REVIEW_RATING      CHECK ("REVIEW_RATING" BETWEEN 1 AND 5),
    CONSTRAINT FK_REVIEW_MEMBER       FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"       ("MEMBER_NO"),
    CONSTRAINT FK_REVIEW_ORDER_DETAIL FOREIGN KEY ("DETAIL_ID") REFERENCES "ORDER_DETAIL" ("DETAIL_ID")
);

-- [수정] REPLY_DATE DEFAULT SYSDATE 제거 (답변 전 날짜 자동입력 방지)
CREATE TABLE "INQUIRY" (
    "INQUIRY_ID"       NUMBER        NOT NULL,
    "MEMBER_NO"        NUMBER        NOT NULL,
    "INQUIRY_TYPE"     VARCHAR2(30)  NULL,
    "INQUIRY_CONTENT"  VARCHAR2(400) NULL,
    "INQUIRY_PHOTO"    VARCHAR2(300) NULL,
    "INQUIRY_PW"       VARCHAR2(100) NULL,
    "INQUIRY_REG_DATE" DATE DEFAULT SYSDATE NULL,
    "REPLY_CONTENT"    VARCHAR2(400) NULL,
    "REPLY_DATE"       DATE          NULL,
    "REPLY_YN"         CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_INQUIRY PRIMARY KEY ("INQUIRY_ID"),
    CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

COMMENT ON COLUMN "INQUIRY"."INQUIRY_TYPE" IS '문의 유형 (상품문의/교환반품)';
COMMENT ON COLUMN "INQUIRY"."REPLY_YN"     IS '답변이 완료되면 Y로';

CREATE TABLE "NOTICE" (
    "NOTICE_ID"        NUMBER        NOT NULL,
    "NOTICE_TITLE"     VARCHAR2(200) NOT NULL,
    "NOTICE_CONTENT"   CLOB          NOT NULL,
    "NOTICE_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "NOTICE_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_NOTICE PRIMARY KEY ("NOTICE_ID")
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ACTIVE_YN" IS 'N으로 바꾸면 보이지 않게';

CREATE TABLE "FAQ" (
    "FAQ_ID"        NUMBER        NOT NULL,
    "FAQ_QUESTION"  VARCHAR2(300) NOT NULL,
    "FAQ_ANSWER"    CLOB          NOT NULL,
    "FAQ_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "FAQ_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_FAQ PRIMARY KEY ("FAQ_ID")
);

COMMENT ON COLUMN "FAQ"."FAQ_ACTIVE_YN" IS 'N으로 바꾸면 보이지 않게';

-- [수정] BOARD_TYPE_NAME: VARCHAR -> VARCHAR2

-- =========================
-- COMMUNITY DB FULL SETUP
-- =========================

-- 1. BOARD TYPE
CREATE TABLE BOARD_TYPE (
    BOARD_CODE NUMBER NOT NULL,
    BOARD_TYPE_NAME VARCHAR2(20) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD_TYPE PRIMARY KEY (BOARD_CODE),
    CONSTRAINT CK_BOARD_TYPE_STATUS CHECK (STATUS IN ('Y','N'))
);

-- 3. BOARD
CREATE TABLE BOARD (
    BOARD_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    BOARD_CODE NUMBER NOT NULL,
    CATEGORY_CODE NUMBER NOT NULL,
    BOARD_TITLE VARCHAR2(200) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    READ_COUNT NUMBER DEFAULT 0 NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO),
    CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_BOARD_TYPE FOREIGN KEY (BOARD_CODE) REFERENCES BOARD_TYPE(BOARD_CODE),
    CONSTRAINT CK_BOARD_ACTIVE CHECK (BOARD_ACTIVE IN ('Y','N'))
);

-- 4. BOARD IMAGE
CREATE TABLE BOARD_IMG (
    IMG_NO NUMBER NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(200) NOT NULL,
    CHANGE_NAME VARCHAR2(200) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    FILE_LEVEL NUMBER NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOARD_IMG PRIMARY KEY (IMG_NO),
    CONSTRAINT FK_BOARD_IMG_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
);

-- 5. BOARD_COMMENT 
CREATE TABLE BOARD_COMMENT (
    COMMENT_ID NUMBER NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
    COMMENT_REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    COMMENT_ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD_COMMENT PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_BC_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    CONSTRAINT FK_BC_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT CK_BC_ACTIVE CHECK (COMMENT_ACTIVE_YN IN ('Y','N'))
);

-- 6. REPORT TYPE
CREATE TABLE REPORT_TYPE (
    REPORT_TYPE_ID NUMBER NOT NULL,
    TYPE_NAME VARCHAR2(20) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL, 
    CONSTRAINT PK_REPORT_TYPE PRIMARY KEY (REPORT_TYPE_ID),
    CONSTRAINT UK_REPORT_TYPE_NAME UNIQUE (TYPE_NAME),
    CONSTRAINT CK_REPORT_TYPE_USE CHECK (USE_YN IN ('Y','N'))
);
CREATE TABLE COMMENT_REPORT (
    REPORT_ID NUMBER NOT NULL,
    REPORTER_MEMBER_NO NUMBER NOT NULL,
    COMMENT_ID NUMBER NOT NULL,
    REPORT_TYPE_ID NUMBER NOT NULL,
    REPORT_REASON VARCHAR2(500),
    REPORT_DATE DATE DEFAULT SYSDATE NOT NULL,
    REPORT_PROCESS_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_COMMENT_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_CR_REPORTER FOREIGN KEY (REPORTER_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_CR_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES BOARD_COMMENT(COMMENT_ID),
    CONSTRAINT FK_CR_TYPE FOREIGN KEY (REPORT_TYPE_ID) REFERENCES REPORT_TYPE(REPORT_TYPE_ID),
    CONSTRAINT CK_CR_PROCESS CHECK (REPORT_PROCESS_YN IN ('Y','N'))
); 
-- 8. BOARD LIKE 
CREATE TABLE BOARD_LIKE (
    BOARD_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    LIKE_TYPE CHAR(1) NOT NULL,
    CONSTRAINT PK_BOARD_LIKE PRIMARY KEY (BOARD_NO, MEMBER_NO),
    CONSTRAINT FK_BL_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    CONSTRAINT FK_BL_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT CK_BOARD_LIKE_TYPE CHECK (LIKE_TYPE IN ('L','D'))
);
-- 9. BOARD_CATEGORY
CREATE TABLE BOARD_CATEGORY (
    CATEGORY_CODE NUMBER NOT NULL,
    BOARD_CODE NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(20) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD_CATEGORY PRIMARY KEY (CATEGORY_CODE),
    CONSTRAINT FK_BOARD_CATEGORY_TYPE FOREIGN KEY (BOARD_CODE)
        REFERENCES BOARD_TYPE(BOARD_CODE),
    CONSTRAINT CK_BOARD_CATEGORY_STATUS CHECK (STATUS IN ('Y', 'N'))
);

CREATE TABLE AUTHORITIES (
    MEMBER_NO  NUMBER       NOT NULL,
    AUTHORITY  VARCHAR2(15) NULL,
    CONSTRAINT PK_AUTHORITIES PRIMARY KEY (MEMBER_NO),
    CONSTRAINT FK_AUTHORITIES_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

CREATE TABLE PERSISTENT_LOGINS (
    TOKEN     VARCHAR2(64) NULL,
    SERIES    VARCHAR2(64) NULL,
    LAST_USED TIMESTAMP(6) NULL,
    USERNAME  VARCHAR2(64) NULL
);

CREATE TABLE PRODUCT_CATEGORY (
    CATEGORY_ID        NUMBER       NOT NULL,
    CATEGORY_NAME      VARCHAR2(50) NOT NULL,
    CATEGORY_PARENT_ID NUMBER       NULL,
    CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE PRODUCT_CATEGORY ADD CONSTRAINT FK_PRODUCT_CATEGORY_SELF
    FOREIGN KEY (CATEGORY_PARENT_ID) REFERENCES PRODUCT_CATEGORY (CATEGORY_ID);

CREATE TABLE COMPANY (
    COMPANY_CODE    NUMBER        NOT NULL,
    COMPANY_NAME    VARCHAR2(100) NULL,
    COMPANY_PHONE   VARCHAR2(20)  NULL,
    ADDRESS_ADDRESS VARCHAR2(200) NULL,
    CONSTRAINT PK_COMPANY PRIMARY KEY (COMPANY_CODE)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID        NUMBER        NOT NULL,
    CATEGORY_ID       NUMBER        NOT NULL,
    COMPANY_CODE      NUMBER        NOT NULL,
    PRODUCT_NAME      VARCHAR2(200) NOT NULL,
    PRODUCT_PRICE     NUMBER        NOT NULL,
    PRODUCT_STOCK     NUMBER DEFAULT 0 NOT NULL,
    PRODUCT_DETAIL    CLOB          NOT NULL,
    PRODUCT_PHOTO1    VARCHAR2(300) NOT NULL,
    PRODUCT_PHOTO2    VARCHAR2(300) NULL,
    PRODUCT_REG_DATE  DATE DEFAULT SYSDATE NOT NULL,
    PRODUCT_ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    PET_TYPE          VARCHAR2(10)  NULL,
    AGE_GROUP         VARCHAR2(10)  NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID)  REFERENCES PRODUCT_CATEGORY (CATEGORY_ID),
    CONSTRAINT FK_PRODUCT_COMPANY  FOREIGN KEY (COMPANY_CODE) REFERENCES COMPANY (COMPANY_CODE)
);

CREATE TABLE PET (
    PET_NO     NUMBER        NOT NULL,
    MEMBER_NO  NUMBER        NOT NULL,
    PET_TYPE   VARCHAR2(20)  NOT NULL,
    PET_NAME   VARCHAR2(50)  NOT NULL,
    PET_AGE    DATE          NULL,
    PET_WEIGHT NUMBER(5,2)   NULL,
    PET_PHOTO  VARCHAR2(300) NULL,
    CONSTRAINT PK_PET PRIMARY KEY (PET_NO),
    CONSTRAINT FK_PET_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

CREATE TABLE CART (
    CART_ID       NUMBER NOT NULL,
    MEMBER_NO     NUMBER NOT NULL,
    PRODUCT_ID    NUMBER NOT NULL,
    CART_QTY      NUMBER NOT NULL,
    CART_REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CART PRIMARY KEY (CART_ID),
    CONSTRAINT FK_CART_MEMBER  FOREIGN KEY (MEMBER_NO)  REFERENCES MEMBER  (MEMBER_NO),
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE WISHLIST (
    WISH_ID    NUMBER NOT NULL,
    MEMBER_NO  NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    WISH_DATE  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_WISHLIST PRIMARY KEY (WISH_ID),
    CONSTRAINT FK_WISHLIST_MEMBER  FOREIGN KEY (MEMBER_NO)  REFERENCES MEMBER  (MEMBER_NO),
    CONSTRAINT FK_WISHLIST_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE RECENTLY_VIEWED (
    VIEW_ID     NUMBER NOT NULL,
    MEMBER_NO   NUMBER NOT NULL,
    PRODUCT_ID  NUMBER NOT NULL,
    VIEWED_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RECENTLY_VIEWED PRIMARY KEY (VIEW_ID),
    CONSTRAINT FK_RECENTLY_VIEWED_MEMBER  FOREIGN KEY (MEMBER_NO)  REFERENCES MEMBER  (MEMBER_NO),
    CONSTRAINT FK_RECENTLY_VIEWED_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID            NUMBER        NOT NULL,
    MEMBER_NO           NUMBER        NOT NULL,
    ORDER_DATE          DATE DEFAULT SYSDATE NOT NULL,
    ORDER_TOTAL_PRICE   NUMBER        NOT NULL,
    ORDER_DELIVERY_FEE  NUMBER        NOT NULL,
    ORDERER_NAME        VARCHAR2(50)  NOT NULL,
    ORDERER_PHONE       VARCHAR2(20)  NOT NULL,
    ORDERER_EMAIL       VARCHAR2(100) NULL,
    RECV_NAME           VARCHAR2(50)  NOT NULL,
    RECV_ADDRESS        VARCHAR2(200) NOT NULL,
    RECV_PHONE          VARCHAR2(20)  NOT NULL,
    ORDER_MEMO          VARCHAR2(300) NULL,
    ORDER_CANCEL_YN     CHAR(1) DEFAULT 'N' NOT NULL,
    CANCEL_REQUEST_DATE DATE          NULL,
    CANCEL_REASON       VARCHAR2(200) NULL,
    CANCEL_STATUS       VARCHAR2(10)  NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

CREATE TABLE ORDER_DETAIL (
    DETAIL_ID    NUMBER NOT NULL,
    ORDER_ID     NUMBER NOT NULL,
    PRODUCT_ID   NUMBER NOT NULL,
    DETAIL_QTY   NUMBER NULL,
    DETAIL_PRICE NUMBER NULL,
    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (DETAIL_ID),
    CONSTRAINT FK_ORDER_DETAIL_ORDERS  FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS  (ORDER_ID),
    CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE DELIVERY (
    DELIVERY_ID   NUMBER       NOT NULL,
    ORDER_ID      NUMBER       NOT NULL,
    COURIER       VARCHAR2(50) NULL,
    EXPECTED_DATE DATE         NULL,
    CONSTRAINT PK_DELIVERY PRIMARY KEY (DELIVERY_ID),
    CONSTRAINT FK_DELIVERY_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE STATUS (
    DNUM            VARCHAR2(50) NOT NULL,
    DELIVERY_YN     CHAR(1)      NULL,
    DELIVERY_STATUS VARCHAR2(20) NOT NULL,
    DELIVERY_ID     NUMBER       NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY (DNUM),
    CONSTRAINT FK_STATUS_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY (DELIVERY_ID)
);
CREATE SEQUENCE SEQ_MEMBER          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROD_CAT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COMPANY       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PET             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WISH            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VIEW            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETAIL          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELIVERY        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INQUIRY         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAQ             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BRD_TYPE         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BRD_CAT      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FILE            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COMMENT         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_REPORT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPORT_TYPE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOARD_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- ========================================
-- 🔥 전체 DROP (있으면만)
-- ========================================
DROP TABLE COMMENT_REPORT PURGE;
DROP TABLE BOARD_COMMENT PURGE;
DROP TABLE BOARD_IMG PURGE;
DROP TABLE BOARD_LIKE PURGE;
DROP TABLE BOARD PURGE;
DROP TABLE BOARD_CATEGORY PURGE;
DROP TABLE BOARD_TYPE PURGE;
DROP TABLE REPORT_TYPE PURGE;
DROP TABLE MEMBER PURGE;

-- ========================================
-- 🔥 시퀀스 DROP
-- ========================================
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_BOARD_IMG_NO;
DROP SEQUENCE SEQ_COMMENT_ID;
DROP SEQUENCE SEQ_COMMENT_REPORT_ID;
DROP SEQUENCE SEQ_REPORT_TYPE_ID;
DROP SEQUENCE SEQ_MEMBER_NO;

--------------------------------------------------
-- ========================================
-- 🔥 MEMBER
-- ========================================
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    MEMBER_PWD VARCHAR2(255) NOT NULL,
    MEMBER_NAME VARCHAR2(50),
    MEMBER_ADDRESS VARCHAR2(200),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    MEMBER_JOIN_DATE DATE DEFAULT SYSDATE,
    MEMBER_ACTIVE_YN CHAR(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------
-- ========================================
-- 🔥 BOARD_TYPE (필수)
-- ========================================
CREATE TABLE BOARD_TYPE (
    BOARD_CODE NUMBER PRIMARY KEY,
    BOARD_TYPE_NAME VARCHAR2(20) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y'
);

INSERT INTO BOARD_TYPE VALUES (1, '우리아이 자랑', 'Y');
INSERT INTO BOARD_TYPE VALUES (2, '육아 꿀팁', 'Y');
INSERT INTO BOARD_TYPE VALUES (3, '자유 게시판', 'Y');

--------------------------------------------------
-- ========================================
-- 🔥 BOARD_CATEGORY
-- ========================================
CREATE TABLE BOARD_CATEGORY (
    CATEGORY_CODE NUMBER PRIMARY KEY,
    BOARD_CODE NUMBER,
    CATEGORY_NAME VARCHAR2(20),
    STATUS CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (BOARD_CODE) REFERENCES BOARD_TYPE(BOARD_CODE)
);

-- 기본 카테고리
INSERT INTO BOARD_CATEGORY VALUES (101, 2, '강아지', 'Y');
INSERT INTO BOARD_CATEGORY VALUES (102, 2, '고양이', 'Y');
INSERT INTO BOARD_CATEGORY VALUES (103, 2, '공통', 'Y');

INSERT INTO BOARD_CATEGORY VALUES (201, 3, '질문', 'Y');
INSERT INTO BOARD_CATEGORY VALUES (202, 3, '고민', 'Y');
INSERT INTO BOARD_CATEGORY VALUES (203, 3, '자유', 'Y');

--------------------------------------------------
-- ========================================
-- 🔥 BOARD
-- ========================================
CREATE TABLE BOARD (
    BOARD_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    BOARD_CODE NUMBER NOT NULL,
    CATEGORY_CODE NUMBER,
    BOARD_TITLE VARCHAR2(200),
    BOARD_CONTENT VARCHAR2(4000),
    READ_COUNT NUMBER DEFAULT 0,
    CREATE_DATE DATE DEFAULT SYSDATE,
    BOARD_ACTIVE CHAR(1) DEFAULT 'Y',

    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (BOARD_CODE) REFERENCES BOARD_TYPE(BOARD_CODE)
);

CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------
-- ========================================
-- 🔥 BOARD_IMG
-- ========================================
CREATE TABLE BOARD_IMG (
    IMG_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER,
    ORIGIN_NAME VARCHAR2(200),
    CHANGE_NAME VARCHAR2(200),
    FILE_PATH VARCHAR2(500),
    FILE_LEVEL NUMBER,
    UPLOAD_DATE DATE DEFAULT SYSDATE,

    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
);

CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------
-- ========================================
-- 🔥 BOARD_COMMENT
-- ========================================
CREATE TABLE BOARD_COMMENT (
    COMMENT_ID NUMBER PRIMARY KEY,
    BOARD_NO NUMBER,
    MEMBER_NO NUMBER,
    COMMENT_CONTENT VARCHAR2(1000),
    COMMENT_REG_DATE DATE DEFAULT SYSDATE,
    COMMENT_ACTIVE_YN CHAR(1) DEFAULT 'Y',

    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

CREATE SEQUENCE SEQ_COMMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------
-- ========================================
-- 🔥 REPORT_TYPE
-- ========================================
CREATE TABLE REPORT_TYPE (
    REPORT_TYPE_ID NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(20) UNIQUE,
    USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_REPORT_TYPE_ID START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO REPORT_TYPE VALUES (1, '욕설', 'Y');
INSERT INTO REPORT_TYPE VALUES (2, '광고', 'Y');
INSERT INTO REPORT_TYPE VALUES (3, '기타', 'Y');

--------------------------------------------------
-- ========================================
-- 🔥 COMMENT_REPORT
-- ========================================
CREATE TABLE COMMENT_REPORT (
    REPORT_ID NUMBER PRIMARY KEY,
    REPORTER_MEMBER_NO NUMBER,
    COMMENT_ID NUMBER,
    REPORT_TYPE_ID NUMBER,
    REPORT_REASON VARCHAR2(500),
    REPORT_DATE DATE DEFAULT SYSDATE,
    REPORT_PROCESS_YN CHAR(1) DEFAULT 'N',

    FOREIGN KEY (REPORTER_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (COMMENT_ID) REFERENCES BOARD_COMMENT(COMMENT_ID),
    FOREIGN KEY (REPORT_TYPE_ID) REFERENCES REPORT_TYPE(REPORT_TYPE_ID)
);

CREATE SEQUENCE SEQ_COMMENT_REPORT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------
-- ========================================
-- 🔥 BOARD_LIKE
-- ========================================
CREATE TABLE BOARD_LIKE (
    BOARD_NO NUMBER,
    MEMBER_NO NUMBER,
    LIKE_TYPE CHAR(1),

    PRIMARY KEY (BOARD_NO, MEMBER_NO),
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

--------------------------------------------------
COMMIT;