-- ============================================================
-- 전체 DROP 후 재생성 DDL
-- FK 참조 순서를 고려해 역순으로 DROP, 정순으로 CREATE
-- ============================================================


-- ============================================================
-- 1. 기존 시퀀스 DROP
-- ============================================================

DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_PROD_CAT;
DROP SEQUENCE SEQ_COMPANY;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_PET;
DROP SEQUENCE SEQ_CART;
DROP SEQUENCE SEQ_WISH;
DROP SEQUENCE SEQ_VIEW;
DROP SEQUENCE SEQ_ORDER;
DROP SEQUENCE SEQ_DETAIL;
DROP SEQUENCE SEQ_DELIVERY;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_INQUIRY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_BRD_TYPE;
DROP SEQUENCE SEQ_BRD_CAT;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_FILE;
DROP SEQUENCE SEQ_COMMENT;
DROP SEQUENCE SEQ_REPORT;


-- ============================================================
-- 2. 기존 테이블 DROP (FK 참조 역순)
-- ============================================================

DROP TABLE "COMMENT_REPORT"    PURGE;
DROP TABLE "COMMENT"           PURGE;
DROP TABLE "BOARD_LIKE"        PURGE;
DROP TABLE "BOARD_FILE"        PURGE;
DROP TABLE "BOARD"             PURGE;
DROP TABLE "BOARD_CATEGORY"    PURGE;
DROP TABLE "BOARD_TYPE"        PURGE;
DROP TABLE "FAQ"               PURGE;
DROP TABLE "NOTICE"            PURGE;
DROP TABLE "INQUIRY"           PURGE;
DROP TABLE "REVIEW"            PURGE;
DROP TABLE "STATUS"            PURGE;
DROP TABLE "DELIVERY"          PURGE;
DROP TABLE "ORDER_DETAIL"      PURGE;
DROP TABLE "ORDERS"            PURGE;
DROP TABLE "RECENTLY_VIEWED"   PURGE;
DROP TABLE "WISHLIST"          PURGE;
DROP TABLE "CART"              PURGE;
DROP TABLE "PET"               PURGE;
DROP TABLE "PRODUCT"           PURGE;
DROP TABLE "PRODUCT_CATEGORY"  PURGE;
DROP TABLE "COMPANY"           PURGE;
DROP TABLE "PERSISTENT_LOGINS" PURGE;
DROP TABLE "AUTHORITIES"       PURGE;
DROP TABLE "MEMBER"            PURGE;


-- ============================================================
-- 3. 시퀀스 생성
-- ============================================================

CREATE SEQUENCE SEQ_MEMBER          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROD_CAT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COMPANY       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PET             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WISH            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VIEW            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETAIL          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELIVERY        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INQUIRY         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAQ             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BRD_TYPE         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BRD_CAT      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FILE            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COMMENT         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ============================================================
-- 4. 테이블 생성 (FK 참조 정순)
-- ============================================================

CREATE TABLE "MEMBER" (
    "MEMBER_NO"         NUMBER          NOT NULL,
    "MEMBER_ID"         VARCHAR2(50)    NOT NULL,
    "MEMBER_PWD"         VARCHAR2(255)   NOT NULL,
    "MEMBER_NAME"       VARCHAR2(50)    NOT NULL,
    "MEMBER_ADDRESS"    VARCHAR2(200)   NOT NULL,
    "PHONE"             VARCHAR2(20)    NOT NULL,
    "EMAIL"             VARCHAR2(100)   NULL,
    "MEMBER_JOIN_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "MEMBER_ACTIVE_YN"  CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY ("MEMBER_NO")
);

CREATE TABLE "AUTHORITIES" (
    "MEMBER_NO"  NUMBER       NOT NULL,
    "AUTHORITY"  VARCHAR2(15) NULL,
    CONSTRAINT PK_AUTHORITIES PRIMARY KEY ("MEMBER_NO"),
    CONSTRAINT FK_AUTHORITIES_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "PERSISTENT_LOGINS" (
    "TOKEN"     VARCHAR2(64) NULL,
    "SERIES"    VARCHAR2(64) NULL,
    "LAST_USED" TIMESTAMP(6) NULL,
    "USERNAME"  VARCHAR2(64) NULL
);

-- [수정] CATEGORY_PARENT_ID: NOT NULL -> NULL (NULL=최상위 카테고리)
CREATE TABLE "PRODUCT_CATEGORY" (
    "CATEGORY_ID"        NUMBER       NOT NULL,
    "CATEGORY_NAME"      VARCHAR2(50) NOT NULL,
    "CATEGORY_PARENT_ID" NUMBER       NULL,
    CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY ("CATEGORY_ID")
);

COMMENT ON COLUMN "PRODUCT_CATEGORY"."CATEGORY_PARENT_ID" IS '상위 카테고리 ID (자기참조, NULL=최상위)';

ALTER TABLE "PRODUCT_CATEGORY" ADD CONSTRAINT FK_PRODUCT_CATEGORY_SELF
    FOREIGN KEY ("CATEGORY_PARENT_ID") REFERENCES "PRODUCT_CATEGORY" ("CATEGORY_ID");

CREATE TABLE "COMPANY" (
    "COMPANY_CODE"    NUMBER        NOT NULL,
    "COMPANY_NAME"    VARCHAR2(100) NULL,
    "COMPANY_PHONE"   VARCHAR2(20)  NULL,
    "ADDRESS_ADDRESS" VARCHAR2(200) NULL,
    CONSTRAINT PK_COMPANY PRIMARY KEY ("COMPANY_CODE")
);

CREATE TABLE "PRODUCT" (
    "PRODUCT_ID"        NUMBER        NOT NULL,
    "CATEGORY_ID"       NUMBER        NOT NULL,
    "COMPANY_CODE"      NUMBER        NOT NULL,
    "PRODUCT_NAME"      VARCHAR2(200) NOT NULL,
    "PRODUCT_PRICE"     NUMBER        NOT NULL,
    "PRODUCT_STOCK"     NUMBER DEFAULT 0 NOT NULL,
    "PRODUCT_DETAIL"    CLOB          NOT NULL,
    "PRODUCT_PHOTO1"    VARCHAR2(300) NOT NULL,
    "PRODUCT_PHOTO2"    VARCHAR2(300) NULL,
    "PRODUCT_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "PRODUCT_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    "PET_TYPE"          VARCHAR2(10)  NULL,
    "AGE_GROUP"         VARCHAR2(10)  NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY ("PRODUCT_ID"),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY ("CATEGORY_ID")  REFERENCES "PRODUCT_CATEGORY" ("CATEGORY_ID"),
    CONSTRAINT FK_PRODUCT_COMPANY  FOREIGN KEY ("COMPANY_CODE") REFERENCES "COMPANY"          ("COMPANY_CODE")
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_ACTIVE_YN" IS '품절되면 N으로 바뀌게';

CREATE TABLE "PET" (
    "PET_NO"     NUMBER        NOT NULL,
    "MEMBER_NO"  NUMBER        NOT NULL,
    "PET_TYPE"   VARCHAR2(20)  NOT NULL,
    "PET_NAME"   VARCHAR2(50)  NOT NULL,
    "PET_AGE"    DATE          NULL,
    "PET_WEIGHT" NUMBER(5,2)   NULL,
    "PET_PHOTO"  VARCHAR2(300) NULL,
    CONSTRAINT PK_PET PRIMARY KEY ("PET_NO"),
    CONSTRAINT FK_PET_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

COMMENT ON COLUMN "PET"."PET_PHOTO" IS '사진 파일 경로 (서버 상대경로)';

CREATE TABLE "CART" (
    "CART_ID"       NUMBER NOT NULL,
    "MEMBER_NO"     NUMBER NOT NULL,
    "PRODUCT_ID"    NUMBER NOT NULL,
    "CART_QTY"      NUMBER NOT NULL,
    "CART_REG_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CART PRIMARY KEY ("CART_ID"),
    CONSTRAINT FK_CART_MEMBER  FOREIGN KEY ("MEMBER_NO")  REFERENCES "MEMBER"  ("MEMBER_NO"),
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "WISHLIST" (
    "WISH_ID"    NUMBER NOT NULL,
    "MEMBER_NO"  NUMBER NOT NULL,
    "PRODUCT_ID" NUMBER NOT NULL,
    "WISH_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_WISHLIST PRIMARY KEY ("WISH_ID"),
    CONSTRAINT FK_WISHLIST_MEMBER  FOREIGN KEY ("MEMBER_NO")  REFERENCES "MEMBER"  ("MEMBER_NO"),
    CONSTRAINT FK_WISHLIST_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "RECENTLY_VIEWED" (
    "VIEW_ID"     NUMBER NOT NULL,
    "MEMBER_NO"   NUMBER NOT NULL,
    "PRODUCT_ID"  NUMBER NOT NULL,
    "VIEWED_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RECENTLY_VIEWED PRIMARY KEY ("VIEW_ID"),
    CONSTRAINT FK_RECENTLY_VIEWED_MEMBER  FOREIGN KEY ("MEMBER_NO")  REFERENCES "MEMBER"  ("MEMBER_NO"),
    CONSTRAINT FK_RECENTLY_VIEWED_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "ORDERS" (
    "ORDER_ID"            NUMBER        NOT NULL,
    "MEMBER_NO"           NUMBER        NOT NULL,
    "ORDER_DATE"          DATE DEFAULT SYSDATE NOT NULL,
    "ORDER_TOTAL_PRICE"   NUMBER        NOT NULL,
    "ORDER_DELIVERY_FEE"  NUMBER        NOT NULL,
    "ORDERER_NAME"        VARCHAR2(50)  NOT NULL,
    "ORDERER_PHONE"       VARCHAR2(20)  NOT NULL,
    "ORDERER_EMAIL"       VARCHAR2(100) NULL,
    "RECV_NAME"           VARCHAR2(50)  NOT NULL,
    "RECV_ADDRESS"        VARCHAR2(200) NOT NULL,
    "RECV_PHONE"          VARCHAR2(20)  NOT NULL,
    "ORDER_MEMO"          VARCHAR2(300) NULL,
    "ORDER_CANCEL_YN"     CHAR(1) DEFAULT 'N' NOT NULL,
    "CANCEL_REQUEST_DATE" DATE          NULL,
    "CANCEL_REASON"       VARCHAR2(200) NULL,
    "CANCEL_STATUS"       VARCHAR2(10)  NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY ("ORDER_ID"),
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "ORDER_DETAIL" (
    "DETAIL_ID"    NUMBER NOT NULL,
    "ORDER_ID"     NUMBER NOT NULL,
    "PRODUCT_ID"   NUMBER NOT NULL,
    "DETAIL_QTY"   NUMBER NULL,
    "DETAIL_PRICE" NUMBER NULL,
    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY ("DETAIL_ID"),
    CONSTRAINT FK_ORDER_DETAIL_ORDERS  FOREIGN KEY ("ORDER_ID")   REFERENCES "ORDERS"  ("ORDER_ID"),
    CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
);

CREATE TABLE "DELIVERY" (
    "DELIVERY_ID"   NUMBER       NOT NULL,
    "ORDER_ID"      NUMBER       NOT NULL,
    "COURIER"       VARCHAR2(50) NULL,
    "EXPECTED_DATE" DATE         NULL,
    CONSTRAINT PK_DELIVERY PRIMARY KEY ("DELIVERY_ID"),
    CONSTRAINT FK_DELIVERY_ORDERS FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS" ("ORDER_ID")
);

CREATE TABLE "STATUS" (
    "DNUM"            VARCHAR2(50) NOT NULL,
    "DELIVERY_YN"     CHAR(1)      NULL,
    "DELIVERY_STATUS" VARCHAR2(20) NOT NULL,
    "DELIVERY_ID"     NUMBER       NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY ("DNUM"),
    CONSTRAINT FK_STATUS_DELIVERY FOREIGN KEY ("DELIVERY_ID") REFERENCES "DELIVERY" ("DELIVERY_ID")
);

COMMENT ON COLUMN "STATUS"."DELIVERY_STATUS" IS '배송중/배송완료 둘 중 하나의 값. 배송완료가 Y로 되어 있으면 배송 완료로 값을 변경';

-- [수정] REVIEW_RATING CHECK 제약 추가 (1~5 별점)
CREATE TABLE "REVIEW" (
    "REVIEW_ID"        NUMBER         NOT NULL,
    "MEMBER_NO"        NUMBER         NOT NULL,
    "DETAIL_ID"        NUMBER         NOT NULL,
    "REVIEW_RATING"    NUMBER(1)      NOT NULL,
    "REVIEW_CONTENT"   VARCHAR2(1000) NOT NULL,
    "REVIEW_PHOTO"     VARCHAR2(300)  NULL,
    "REVIEW_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "REVIEW_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REVIEW PRIMARY KEY ("REVIEW_ID"),
    CONSTRAINT CHK_REVIEW_RATING      CHECK ("REVIEW_RATING" BETWEEN 1 AND 5),
    CONSTRAINT FK_REVIEW_MEMBER       FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"       ("MEMBER_NO"),
    CONSTRAINT FK_REVIEW_ORDER_DETAIL FOREIGN KEY ("DETAIL_ID") REFERENCES "ORDER_DETAIL" ("DETAIL_ID")
);

-- [수정] REPLY_DATE DEFAULT SYSDATE 제거 (답변 전 날짜 자동입력 방지)
CREATE TABLE "INQUIRY" (
    "INQUIRY_ID"       NUMBER        NOT NULL,
    "MEMBER_NO"        NUMBER        NOT NULL,
    "INQUIRY_TYPE"     VARCHAR2(30)  NULL,
    "INQUIRY_CONTENT"  VARCHAR2(400) NULL,
    "INQUIRY_PHOTO"    VARCHAR2(300) NULL,
    "INQUIRY_PW"       VARCHAR2(100) NULL,
    "INQUIRY_REG_DATE" DATE DEFAULT SYSDATE NULL,
    "REPLY_CONTENT"    VARCHAR2(400) NULL,
    "REPLY_DATE"       DATE          NULL,
    "REPLY_YN"         CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_INQUIRY PRIMARY KEY ("INQUIRY_ID"),
    CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

COMMENT ON COLUMN "INQUIRY"."INQUIRY_TYPE" IS '문의 유형 (상품문의/교환반품)';
COMMENT ON COLUMN "INQUIRY"."REPLY_YN"     IS '답변이 완료되면 Y로';

CREATE TABLE "NOTICE" (
    "NOTICE_ID"        NUMBER        NOT NULL,
    "NOTICE_TITLE"     VARCHAR2(200) NOT NULL,
    "NOTICE_CONTENT"   CLOB          NOT NULL,
    "NOTICE_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "NOTICE_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_NOTICE PRIMARY KEY ("NOTICE_ID")
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ACTIVE_YN" IS 'N으로 바꾸면 보이지 않게';

CREATE TABLE "FAQ" (
    "FAQ_ID"        NUMBER        NOT NULL,
    "FAQ_QUESTION"  VARCHAR2(300) NOT NULL,
    "FAQ_ANSWER"    CLOB          NOT NULL,
    "FAQ_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "FAQ_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_FAQ PRIMARY KEY ("FAQ_ID")
);

COMMENT ON COLUMN "FAQ"."FAQ_ACTIVE_YN" IS 'N으로 바꾸면 보이지 않게';

-- [수정] BOARD_TYPE_NAME: VARCHAR -> VARCHAR2
CREATE TABLE "BOARD_TYPE" (
    "BOARD_CODE"      NUMBER       NOT NULL,
    "BOARD_TYPE_NAME" VARCHAR2(20) NOT NULL,
    "STATUS"          CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD_TYPE PRIMARY KEY ("BOARD_CODE")
);

CREATE TABLE "BOARD_CATEGORY" (
    "CATEGORY_CODE" NUMBER       NOT NULL,
    "BOARD_CODE"    NUMBER       NOT NULL,
    "CATEGORY_NAME" VARCHAR2(20) NOT NULL,
    "STATUS"        CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD_CATEGORY PRIMARY KEY ("CATEGORY_CODE"),
    CONSTRAINT FK_BOARD_CATEGORY_TYPE FOREIGN KEY ("BOARD_CODE") REFERENCES "BOARD_TYPE" ("BOARD_CODE")
);

CREATE TABLE "BOARD" (
    "BOARD_NO"      NUMBER         NOT NULL,
    "MEMBER_NO"     NUMBER         NOT NULL,
    "CATEGORY_CODE" NUMBER         NOT NULL,
    "BOARD_TITLE"   VARCHAR2(200)  NOT NULL,
    "BOARD_CONTENT" VARCHAR2(4000) NOT NULL,
    "VIEW_COUNT"    NUMBER         NOT NULL,
    "CREATE_DATE"   DATE DEFAULT SYSDATE NOT NULL,
    "BOARD_ACTIVE"  CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY ("BOARD_NO"),
    CONSTRAINT FK_BOARD_MEMBER   FOREIGN KEY ("MEMBER_NO")     REFERENCES "MEMBER"         ("MEMBER_NO"),
    CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY ("CATEGORY_CODE") REFERENCES "BOARD_CATEGORY" ("CATEGORY_CODE")
);

CREATE TABLE "BOARD_FILE" (
    "FILE_NO"     NUMBER        NOT NULL,
    "BOARD_NO"    NUMBER        NOT NULL,
    "ORIGIN_NAME" VARCHAR2(200) NOT NULL,
    "CHANGE_NAME" VARCHAR2(200) NOT NULL,
    "FILE_PATH"   VARCHAR2(500) NOT NULL,
    "FILE_LEVEL"  NUMBER        NOT NULL,
    "UPLOAD_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOARD_FILE PRIMARY KEY ("FILE_NO"),
    CONSTRAINT FK_BOARD_FILE_BOARD FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO")
);

CREATE TABLE "BOARD_LIKE" (
    "BOARD_NO"  NUMBER  NOT NULL,
    "MEMBER_NO" NUMBER  NOT NULL,
    "LIKE_TYPE" CHAR(1) NOT NULL,
    CONSTRAINT PK_BOARD_LIKE PRIMARY KEY ("BOARD_NO", "MEMBER_NO"),
    CONSTRAINT FK_BOARD_LIKE_BOARD  FOREIGN KEY ("BOARD_NO")  REFERENCES "BOARD"  ("BOARD_NO"),
    CONSTRAINT FK_BOARD_LIKE_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

-- [수정] MEMBER_NO2 -> BOARD_NO 컬럼명 변경 (댓글이 달린 게시글 참조)
CREATE TABLE "COMMENT" (
    "COMMENT_ID"        NUMBER         NOT NULL,
    "BOARD_NO"          NUMBER         NOT NULL,
    "MEMBER_NO"         NUMBER         NOT NULL,
    "COMMENT_CONTENT"   VARCHAR2(1000) NOT NULL,
    "COMMENT_REG_DATE"  DATE DEFAULT SYSDATE NOT NULL,
    "COMMENT_ACTIVE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY ("COMMENT_ID"),
    CONSTRAINT FK_COMMENT_BOARD  FOREIGN KEY ("BOARD_NO")  REFERENCES "BOARD"  ("BOARD_NO"),
    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "COMMENT_REPORT" (
    "REPORT_ID"         NUMBER        NOT NULL,
    "COMMENT_ID"        NUMBER        NOT NULL,
    "REPORT_TYPE"       VARCHAR2(50)  NOT NULL,
    "REPORT_REASON"     VARCHAR2(500) NULL,
    "REPORT_DATE"       DATE DEFAULT SYSDATE NOT NULL,
    "REPORT_PROCESS_YN" CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_COMMENT_REPORT PRIMARY KEY ("REPORT_ID"),
    CONSTRAINT FK_COMMENT_REPORT_COMMENT FOREIGN KEY ("COMMENT_ID") REFERENCES "COMMENT" ("COMMENT_ID")
);

COMMENT ON COLUMN "COMMENT_REPORT"."REPORT_PROCESS_YN" IS '처리가 완료되면 Y로 바꾼다';